### PR TITLE
http://xxxx/#/ is detected as a path param when useHash flag is true

### PR DESCRIPTION
**Pull request by kgston**
Fixed case where the useHash flag is on but the resolve function detects /#/ as a parameter given a route "/:pathParams"

Added "/#" to the root when the flag is true to resolve this issue

### CODE REVIEW

**Comment by krasimir** [comment]
Thanks for the PR. I'll check it soon and will get back to you.

**Comment by krasimir** [comment]
Can you please come with a test case. I first wrote a test where the root is `site.com`, the pattern route is `/:foo` and I resolved it with `site.com/#bar` or `site.com/#/bar`. Your change didn't solve the issue so I made one commit that makes the test green. What's exactly the case that your PR covers?

**Comment by kgston** [comment]
Apologies for the lack of details. I have added 2 test cases to your testing suite to describe the bugs I faced. I didn't have much time to properly learn the chai syntax, so I just hacked some tests with the assert API. Please feel free to amend to your testing style.

As for the code, the test cases passes on your test suite because of the way the URL is constructed at the start of the testing page, basically `http://site.com/testing`. When the router is activated, it becomes `http://site.com/testing#xxxx`. In the project that I'm working on, we start the router at the root url, meaning `http://site.com/` so it ends up as `http://site.com/#`. The important difference is the `/` before the `#`. I have attempted to simulated this in the test script by destroying the main site router first. It is rather hacky, so apologies. Please rectify as required. I hope this better describes the problem.

**Comment by krasimir** [comment]
`1.2.5` version is released containing your fix. Thanks for contribution. I'll close this PR because the tests that you added break the navigation on the demo site.

**Comment by kgston** [comment]
Thanks!

**Pull request closed without merging**
