### PR TITLE
Provide fallback capability

### PR DESCRIPTION
**Pull request by iamwyza**
Allows user to specify function to call in the event that no routes
match.

router.fallback(function(url, params) {
console.log('Failed to find route');
console.log(url);
console.log(params);
});

### CODE REVIEW

**Comment by fourpixels** [comment]
I would try to find a better name, as IMO `fallback` is not descriptive at all.

**Comment by iamwyza** [comment]
what about `defaultroute` ?

**Comment by joakimbugge** [comment]
What is the difference between this approach and using asterisk (*)?

**Comment by iamwyza** [comment]
(*) would work, but then you'd have to parse out the parms yourself.  One nice thing about this approach is you get the url & the parms both.  Would provide easier feedback in logs when someone tries to use a non-existent route.

It just rubs against the grain to do a * match instead of specifically stating that a function should be used when no other route matches from a code reading perspective.

**Comment by krasimir** [comment]
Hey guys, sorry for the delay in responding on this PR. Navigo accepts few things in its `on` method. One of them is just a single function. For example:
```js
router.on(function () {
  ...
});
```
This is the same as saying `router.on('', function () { ... })`. What you think if we write:

```js
router.on(function defaultRoute() {
  ...
});
```

**Comment by iamwyza** [comment]
I think as long as you include an example of this in the documentation, then this approach would work quite well.

**Comment by krasimir** [comment]
There was an example of this technique but it wasn't clear that it may be used as a fallback. There is a [dedicated section](https://github.com/krasimir/navigo#fallback-route) now.

**Comment by iamwyza** [comment]
Great! looks good to me.  Thanks!

**Pull request closed without merging**
