### PR TITLE
Use rollup for building, removed compiled files from source control, …

### PR DESCRIPTION
**Pull request by Havunen**
Changes:
- All dependencies updated and their configs changed as needed
- IntelliJ project files added to gitignore
- compiled files removed from source control
- added module entry point to `package.json`
- rollup is now used for building, it provides ES6 output for jsnext:main & module entry points, common-js bundle for main and umd minified bundle for browser. All outputs are in lib folder. ( ***Do build before publish*** )
- Removed some unnecessary (wrong) semicolons from source and simplified two boolean statements

All tests are passing,
I also tested html-template-demo, which seems to work fine. 

NOTE: **_I did not test "basic" demo._**

### CODE REVIEW

**Comment by Havunen** [comment]
Sure. I can do the change later today.

**Comment by Havunen** [comment]
I updated the pull request, lib folder is now added back

**Comment by krasimir** [comment]
Thanks for the update. I think I wasn't clear enough with my previous comment. What I meant is that `lib/navigo.js` should contain the `umd` snippet so could be just dropped on a page and works. I think we should amend [this](https://github.com/krasimir/navigo/pull/187/files#diff-ff6e5f22a9c7e66987b19c0199636480R46) block to:

```js
outputs.push({
  name: 'Navigo',
  format: 'umd',
  file: path.join(__dirname, 'lib', 'navigo.js'),
  sourcemap: false
});
outputs.push({
  name: 'Navigo',
  format: 'cjs',
  file: path.join(__dirname, 'lib', 'navigo.cjs.js'),
  sourcemap: false
});
outputs.push({
  name: 'Navigo',
  format: 'es',
  file: path.join(__dirname, 'lib', 'navigo.es.js'),
  sourcemap: false
});
```

**Comment by Havunen** [comment]
True, lets change it.

**Comment by krasimir** [comment]
Thanks.

**Comment by Havunen** [comment]
Maybe the development process, could be changed to rollup also. So everything would use rollup ( testing, development and build)

**Comment by krasimir** [comment]
Yep, it's in my TODO list. I'll probably do it in the upcoming weekend.

**Comment by krasimir** [comment]
It's done. https://github.com/krasimir/navigo/commit/784277483946e4f1eb74ddcfe94d5038e1ef0e8e

**Comment by Havunen** [comment]
Cool! What about browserify tests?

**Comment by krasimir** [comment]
Yeah, the tests are another beast. I wanna use Jest but that will come later.

**Pull request merged**
