### PR TITLE
Call leave before other hooks and canLeave hook added

### PR DESCRIPTION
**Pull request by BSzabi**

### CODE REVIEW

**Comment by BSzabi** [comment]
e45cfb5: Run callLeave before other hooks
3443f93: Added canLeave hook which runs before changing the route. It can stop the routing progress Usage example: 
`router.on(
  '/something',
  function () {
    // something
  },
{
 canLeave: function (resolve) {
      // doing some async operation
      if(expression == true) {
         //Continue routing
         resolve();
      } else {
          //Stop routing
          resolve(false);
     }
   },
}`

**Comment by krasimir** [comment]
@BSzabi thank you for the PR but can you please make the changes in the file under the `src` folder.

**Comment by BSzabi** [comment]
Sorry, I didn't realised it. I fixed it

**Comment by krasimir** [comment]
The new version 8.0.0 has a `leave` hook that is able to also prevent the leaving. 

```js
router.on("/never-leave", () => {}, {
    leave(done, match) {
      done(false);
    },
  })
```

If `done` is called with `false` the router doesn't leave the given route. In the example above if the user lands on `never-leave` he/she will never be able to open another route.

**Pull request closed without merging**
